# Generated by Django 2.1.5 on 2019-02-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('city_slug', models.CharField(max_length=200)),
                ('city_lat', models.CharField(max_length=60)),
                ('city_lng', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinics_id', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.URLField()),
                ('lat', models.CharField(max_length=60)),
                ('lng', models.CharField(max_length=60)),
                ('city_slug', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=200)),
                ('region_name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('worktime', models.TextField()),
                ('specialities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=20)),
                ('clinics_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=200)),
                ('specialities', models.TextField()),
                ('experience_year', models.CharField(max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('rate_value', models.FloatField(default=0)),
                ('education', models.TextField()),
                ('qualification', models.TextField()),
                ('work_experience', models.TextField()),
                ('specializes_in_diseases', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('date', models.DateField()),
            ],
        ),
    ]
