# Generated by Django 2.2.2 on 2019-06-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190619_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('last_price', models.CharField(max_length=100)),
                ('changed_value', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Clinics',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
