# Generated by Django 2.2.2 on 2019-06-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190619_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='changed_value',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='volume',
        ),
    ]
