# Generated by Django 2.2.2 on 2019-06-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190620_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='changed_value',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='last_price',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(db_index=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
